source 'https://github.com/CocoaPods/Specs.git'

#use_frameworks!

workspace 'RestaurantEvent'

pod 'Parse'
pod 'ParseFacebookUtils'
pod 'ParseCrashReporting'
pod 'ParseUI'
pod 'MBProgressHUD'
pod 'Reachability'
pod 'FormatterKit'
pod 'UIImageEffects'

pod 'JASidePanels'

pod "AZCenterLabelButton"
pod "TPKeyboardAvoiding"

# A collection of categories and class methods to make your iOS life easier.
# pod 'BGUtilities'

# A beautiful set of predefined colors and a set of color methods to make your iOS/OSX development life easier.
# pod 'Colours/Swift'

pod 'Reveal-iOS-SDK'
